<h1>Лабораторная работа 3. Исследование методов работы с матрицами и векторами с помощью библиотеки NumPy<h1>

In [1]:
import numpy as np

<h3>Транспонирование матрицы</h3>

In [2]:
trans_arr = np.matrix('2 4 5; 0 9 8')
print(trans_arr)

[[2 4 5]
 [0 9 8]]


In [3]:
trans = trans_arr.transpose()
print(trans)

[[2 0]
 [4 9]
 [5 8]]


<b>Свойство 1.</b> Дважды транспонированная матрица равна исходной матрице:

In [4]:
trans_a = np.matrix('2 4 5; 1 0 2; 2 8 5')
print(trans_a)

[[2 4 5]
 [1 0 2]
 [2 8 5]]


In [5]:
print((trans_a.T).T)

[[2 4 5]
 [1 0 2]
 [2 8 5]]


<b>Свойство 2.</b> Транспонирование суммы матриц равно сумме транспонированных матриц:

In [6]:
trans_a = np.matrix('2 4 5; 8 9 10')
trans_b = np.matrix('7 8 9; 5 6 1')

In [7]:
trans_l = (trans_a + trans_b).T
print(trans_l)

[[ 9 13]
 [12 15]
 [14 11]]


In [8]:
trans_r = trans_a.T + trans_b.T
print(trans_r)

[[ 9 13]
 [12 15]
 [14 11]]


<b>Свойство 3.</b> Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [9]:
trans_a = np.matrix('2 6; 9 1')
trans_b = np.matrix('5 8; 1 4')

In [10]:
trans_l = (trans_a.dot(trans_b)).T
print(trans_l)

[[16 46]
 [40 76]]


In [11]:
trans_r = (trans_b.T).dot(trans_a.T)
print(trans_r)

[[16 46]
 [40 76]]


<b>Свойство 4.</b>  Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [12]:
trans_a = np.matrix('2 9 7; 1 3 8')
trans_k = 4

In [13]:
trans_l = (trans_k * trans_a).T
print(trans_l)

[[ 8  4]
 [36 12]
 [28 32]]


In [14]:
trans_r = trans_k * (trans_a.T)
print(trans_r)

[[ 8  4]
 [36 12]
 [28 32]]


<h2>Действия над матрицами</h2>

<h3>Умножение матрицы на число</h3>

In [15]:
A = np.matrix('1 1 1; 2 2 2')
B = 8 * A
print(B)

[[ 8  8  8]
 [16 16 16]]


<b>Свойство 1.</b> Произведение единицы и любой заданной матрицы равно заданной матрице:

In [16]:
A = np.matrix('1 1; 2 2')
print(A)

[[1 1]
 [2 2]]


In [17]:
B = A *1
print(B)

[[1 1]
 [2 2]]


<b>Свойство 2.</b> Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [22]:
mult_a = np.matrix("1 2 3; 4 5 6; 7 8 9")
mult_p = 2
mult_q = 3

In [23]:
mult_l = (mult_p + mult_q) * mult_a
print(mult_l)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [24]:
mult_r = mult_p * mult_a + mult_q * mult_a
print(mult_r)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


<b>Свойство 3.</b> Произведение матрицы на произведение двух чисел равно произведению второго числа и заданной матрицы, умноженному на первое число:

In [26]:
mult_l = (mult_p * mult_q) * mult_a
print(mult_l)

[[ 6 12 18]
 [24 30 36]
 [42 48 54]]


In [27]:
mult_r = mult_p * (mult_q * mult_a)
print(mult_r)

[[ 6 12 18]
 [24 30 36]
 [42 48 54]]


<b>Свойство 4.</b> Произведение суммы матриц на число равно сумме произведений этих матриц на заданное число:

In [30]:
mult_a = np.matrix('2 2; 4 7')
mult_b = np.matrix('1 6; 9 8')
mult_k = 3

In [34]:
mult_l = mult_k * (mult_a + mult_b)
print(mult_l)

[[ 9 24]
 [39 45]]


In [35]:
mult_r = mult_k * mult_a + mult_k * mult_b
print(mult_r)

[[ 9 24]
 [39 45]]


<h3>Сложение матриц</h3>

In [36]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('1 6; 9 8')

In [37]:
sum_c = sum_a + sum_b
print(sum_c)

[[ 3  8]
 [13 15]]


<b>Свойство 1.</b>  Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [38]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('1 6; 9 8')

In [39]:
sum_l = sum_a + sum_b
print(sum_l)

[[ 3  8]
 [13 15]]


In [40]:
sum_q = sum_b + sum_a
print(sum_q)

[[ 3  8]
 [13 15]]


<b>Свойство 2.</b> Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

In [41]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('1 6; 9 8')
sum_c = np.matrix('3 8; 4 9')

In [42]:
sum_l = sum_a + (sum_b + sum_c)
print(sum_l)

[[ 6 16]
 [17 24]]


In [44]:
sum_q = (sum_a + sum_b) + sum_c
print(sum_q)

[[ 6 16]
 [17 24]]


<b>Свойство 3.</b> Для любой матрицы существует противоположная ей, такая, что их сумма является нулевой матрицей :

In [49]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('0 0; 0 0')

In [50]:
sum_l = sum_a + (-1) * sum_a
print(sum_l)

[[0 0]
 [0 0]]


In [51]:
print(sum_b)

[[0 0]
 [0 0]]


<h3>Умножение матриц</h3>

In [56]:
sum_a = np.matrix('2 2 2; 5 4 7')
sum_b = np.matrix('6 9; 8 2; 4 5')

In [57]:
sum_l = sum_a.dot(sum_b)
print(sum_l)

[[36 32]
 [90 88]]


<b>Свойство 1.</b> Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в котором будет выполняться эта операция:

In [ ]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('6 9; 8 2')
sum_c = np.matrix('2 3; 4 5')

In [61]:
sum_l = sum_a.dot(sum_b.dot(sum_c))
print(sum_l)

[[144 194]
 [360 490]]


In [62]:
sum_q = (sum_a.dot(sum_b)).dot(sum_c)
print(sum_q)

[[144 194]
 [360 490]]


<b>Свойство 2.</b> Дистрибутивность умножения. Произведение матрицы на сумму матриц равно сумме произведений матриц:


In [58]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('6 9; 8 2')
sum_c = np.matrix('2 3; 4 5')

In [59]:
sum_l = sum_a.dot(sum_b + sum_c)
print(sum_l)

[[ 40  38]
 [116  97]]


In [60]:
sum_r = sum_a.dot(sum_b) + sum_a.dot(sum_c)
print(sum_r)

[[ 40  38]
 [116  97]]


<b>Свойство 3.</b> Умножение матриц в общем виде не коммутативно. Это означает, что для матриц не выполняется правило независимости произведения от перестановки множителей:

In [63]:
sum_a = np.matrix('2 2; 4 7')
sum_b = np.matrix('6 9; 8 2')

In [64]:
sum_l = sum_a.dot(sum_b)
print(sum_l)

[[28 22]
 [80 50]]


In [65]:
sum_q = sum_b.dot(sum_a)
print(sum_q)

[[48 75]
 [24 30]]


<h3>Определитель матрицы</h3>

In [66]:
lin_a = np.matrix('4 -1 -2; 19 4 -1; 8 3 1')
print(lin_a)

[[ 4 -1 -2]
 [19  4 -1]
 [ 8  3  1]]


In [67]:
np.linalg.det(lin_a)

4.999999999999997

<b>Свойство 1.</b> Определитель матрицы остается неизменным при ее транспонировании:

In [68]:
lin_a = np.matrix('4 -1 -2; 19 4 -1; 8 3 1')
print(lin_a)

[[ 4 -1 -2]
 [19  4 -1]
 [ 8  3  1]]


In [69]:
print(lin_a.T)

[[ 4 19  8]
 [-1  4  3]
 [-2 -1  1]]


In [70]:
lin_l = round(np.linalg.det(lin_a), 3)
print(lin_l)

5.0


In [72]:
lin_q = round(np.linalg.det(lin_a.T), 3)
print(lin_q)

5.0


<b>Свойство 2.</b> Если у матрицы есть строка или столбец, состоящие из нулей, то определитель такой матрицы равен нулю:

In [73]:
lin_a = np.matrix('4 -1 -2; 0 0 0; 8 3 1')
print(lin_a)

[[ 4 -1 -2]
 [ 0  0  0]
 [ 8  3  1]]


In [74]:
print(np.linalg.det(lin_a))

0.0


<b>Свойство 3.</b> При перестановке строк матрицы знак ее определителя меняется на противоположный:

In [75]:
lin_a = np.matrix('4 -1 -2; 19 4 -1; 8 3 1')
lin_b = np.matrix('19 4 -1; 4 -1 -2; 8 3 1')

In [77]:
print(round(np.linalg.det(lin_a)))

5.0


In [78]:
print(round(np.linalg.det(lin_b)))

-5.0


<b>Свойство 4.</b> Если у матрицы есть две одинаковые строки, то ее определитель равен нулю:

In [80]:
lin_a = np.matrix('4 -1 -2; 4 -1 -2; 8 3 1')
print(lin_a)

[[ 4 -1 -2]
 [ 4 -1 -2]
 [ 8  3  1]]


In [81]:
print(np.linalg.det(lin_a))

0.0


<b>Свойство 5.</b> Если все элементы строки или столбца матрицы умножить на какое-то число, то и определитель будет умножен на это число:

In [86]:
lin_a = np.matrix('4 -1 -2; 7 8 4; 8 3 1')
lin_k = 2
lin_b = lin_a.copy()
lin_b[1, :] = lin_k * lin_b[1, :]
print(lin_b)

[[ 4 -1 -2]
 [14 16  8]
 [ 8  3  1]]


In [87]:
lin_l =  round(np.linalg.det(lin_a), 3)
print(lin_l)

45.0


In [88]:
lin_q =  round(np.linalg.det(lin_b), 3)
print(lin_q)

90.0


<h3>Обратная матрица</h3>

In [89]:
rev_a = np.matrix('2 2; 4 7')

In [90]:
print(np.linalg.inv(lin_a))

[[-0.08888889 -0.11111111  0.26666667]
 [ 0.55555556  0.44444444 -0.66666667]
 [-0.95555556 -0.44444444  0.86666667]]


<b>Свойство 1.</b> Обратная матрица обратной матрицы есть исходная матрица:

In [91]:
rev_a = np.matrix('2 2; 4 7')
print( np.linalg.inv(np.linalg.inv(rev_a)))

[[2. 2.]
 [4. 7.]]


<b>Свойство 2.</b> Обратная матрица транспонированной матрицы равна транспонированной матрице от обратной матрицы:

In [92]:
rev_a = np.matrix('2 2; 4 7')

In [93]:
rev_l = np.linalg.inv(rev_a.T)
print(rev_l)

[[ 1.16666667 -0.66666667]
 [-0.33333333  0.33333333]]


In [95]:
rev_q = (np.linalg.inv(rev_a)).T
print(rev_q)

[[ 1.16666667 -0.66666667]
 [-0.33333333  0.33333333]]


<b>Свойство 3.</b> Обратная матрица произведения матриц равна произведению обратных матриц:

In [98]:
rev_a = np.matrix('2 2; 4 7')
rev_b = np.matrix('6 9; 8 2')

In [99]:
print(np.linalg.inv(rev_a.dot(rev_b)))

[[-0.13888889  0.06111111]
 [ 0.22222222 -0.07777778]]


In [101]:
print(np.linalg.inv(rev_b).dot(np.linalg.inv(rev_a))
)

[[-0.13888889  0.06111111]
 [ 0.22222222 -0.07777778]]


<h3>Матричный метод.</h3>

Рассмотрим систему линейных уравнений:
    <ul>
        <li>x - 2y + 3z - t = 6</li>
        <li>2x + 3y - 4z + 4t = -7</li>
        <li>3x + y - 2z - 2t = 9</li>
        <li>x - 3y + 7z + 6t = -7</li>
    </ul>

In [106]:
mat_k = np.array([[1, -2, 3, -1], [2, 3, -4, 4], [3, 1, -2, -2], [1, -3, 7, 6]])
print(mat_k)

[[ 1 -2  3 -1]
 [ 2  3 -4  4]
 [ 3  1 -2 -2]
 [ 1 -3  7  6]]


In [108]:
mat_d = round(np.linalg.det(mat_k), 3)
print(mat_d)

35.0


In [109]:
mat_l = np.array([[6], [-7], [9], [-7]])
print(mat_l)

[[ 6]
 [-7]
 [ 9]
 [-7]]


In [111]:
mat_k_inv = np.linalg.inv(mat_k)
print(mat_k_inv @ mat_l)

[[ 2.00000000e+00]
 [-1.00000000e+00]
 [-2.66453526e-15]
 [-2.00000000e+00]]


In [113]:
print(np.linalg.solve(mat_k, mat_l))

[[ 2.]
 [-1.]
 [ 0.]
 [-2.]]


<h3>Метод Крамера</h3>

Найти решение СЛАУ при помощи метода Крамера.
    <ul>
        <li>x - 2y + 3z - t = 6</li>
        <li>2x + 3y - 4z + 4t = -7</li>
        <li>3x + y - 2z - 2t = 9</li>
        <li>x - 3y + 7z + 6t = -7</li>
    </ul>


In [135]:
kram_k = np.array([[1, -2, 3, -1], [2, 3, -4, 4], [3, 1, -2, -2], [1, -3, 7, 6]])
kram_l = np.array([[6], [-7], [9], [-7]])
print(kram_k)

[[ 1 -2  3 -1]
 [ 2  3 -4  4]
 [ 3  1 -2 -2]
 [ 1 -3  7  6]]


In [136]:
kram_d = round(np.linalg.det(kram_k), 3)
print(kram_d)

35.0


In [137]:
kram_temp = np.copy(kram_k)
kram_temp[:, 0] = kram_l[:, 0]
print(kram_temp)

[[ 6 -2  3 -1]
 [-7  3 -4  4]
 [ 9  1 -2 -2]
 [-7 -3  7  6]]


In [138]:
kram_d_1 = np.linalg.det(kram_temp)
print(kram_d_1)

69.99999999999996


In [139]:
kram_temp = np.copy(kram_k)
kram_temp[:, 1] = kram_l[:, 0]

In [140]:
kram_d_2 = np.linalg.det(kram_j)
print(kram_d_2)

-34.99999999999999


In [144]:
kram_temp = np.copy(kram_k)
kram_temp[:, 2] = kram_l[:, 0]

In [146]:
kram_d_3 = np.linalg.det(kram_temp)
print(kram_d_3)

0.0


In [148]:
kram_temp = np.copy(kram_k)
kram_temp[:, 3] = kram_l[:, 0]

In [149]:
kram_d_4 = np.linalg.det(kram_temp)
print(kram_d_4)

-70.00000000000009


In [151]:
print(f"x = {kram_d_1/kram_d} \ny = {kram_d_2/kram_d} \nz = {kram_d_3/kram_d} \nt = {kram_d_4/kram_d}" )

x = 1.999999999999999 
y = -0.9999999999999998 
z = 0.0 
t = -2.000000000000002
