<h1>Лабораторная работа 3. Исследование методов работы с матрицами и векторами с помощью библиотеки NumPy<h1>

In [6]:
import numpy as np

<h3>Транспонирование матрицы</h3>

In [7]:
trans_arr = np.matrix('2 4 5; 0 9 8')
print(trans_arr)

[[2 4 5]
 [0 9 8]]


In [13]:
trans = trans_arr.transpose()
print(trans)

[[2 0]
 [4 9]
 [5 8]]


<b>Свойство 1.</b> Дважды транспонированная матрица равна исходной матрице:

In [14]:
trans_a = np.matrix('2 4 5; 1 0 2; 2 8 5')
print(trans_a)

[[2 4 5]
 [1 0 2]
 [2 8 5]]


In [15]:
print((trans_a.T).T)

[[2 4 5]
 [1 0 2]
 [2 8 5]]


<b>Свойство 2.</b> Транспонирование суммы матриц равно сумме транспонированных матриц:

In [9]:
trans_a = np.matrix('2 4 5; 8 9 10')
trans_b = np.matrix('7 8 9; 5 6 1')

In [10]:
trans_l = (trans_a + trans_b).T
print(trans_l)

[[ 9 13]
 [12 15]
 [14 11]]


In [11]:
trans_r = trans_a.T + trans_b.T
print(trans_r)

[[ 9 13]
 [12 15]
 [14 11]]


<b>Свойство 3.</b> Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [19]:
trans_a = np.matrix('2 6; 9 1')
trans_b = np.matrix('5 8; 1 4')

In [17]:
trans_l = (trans_a.dot(trans_b)).T
print(trans_l)

[[16 46]
 [40 76]]


In [18]:
trans_r = (trans_b.T).dot(trans_a.T)
print(trans_r)

[[16 46]
 [40 76]]


<b>Свойство 4.</b>  Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [22]:
trans_a = np.matrix('2 9 7; 1 3 8')
trans_k = 4

In [23]:
trans_l = (trans_k * trans_a).T
print(trans_l)

[[ 8  4]
 [36 12]
 [28 32]]


In [27]:
trans_r = trans_k * (trans_a.T)
print(f"Ляляля я Саня {trans_r} попопопоп")

Ляляля я Саня [[ 8  4]
 [36 12]
 [28 32]] попопопоп


<h2>Действия над матрицами</h2>

<h3>Умножение матрицы на число</h3>

In [26]:
A = np.matrix('1 1 1; 2 2 2')
B = 8 * A
print(B)

[[ 8  8  8]
 [16 16 16]]


<b>Свойство 1.</b> Произведение единицы и любой заданной матрицы равно заданной матрице:

In [29]:
A = np.matrix('1 1; 2 2')
print(A)

[[1 1]
 [2 2]]


In [30]:
B = A *1
print(B)

[[1 1]
 [2 2]]


<b>Свойство 2.</b> Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю: